stages:
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

build-dotnet-mono:
  stage: build
  image: docker:latest
  script:
    - docker pull "$CI_REGISTRY_IMAGE/dotnet-mono:latest" || true
    - docker build --cache-from "$CI_REGISTRY_IMAGE/dotnet-mono:latest" -t "$CI_REGISTRY_IMAGE/dotnet-mono:latest" dotnet-mono
    - docker push "$CI_REGISTRY_IMAGE/dotnet-mono:latest"
  only: &only_dotnet_mono
    refs:
      - merge_requests
    changes:
      - dotnet-mono/Dockerfile
    
test-dotnet-mono:
  image: "$CI_REGISTRY_IMAGE/dotnet-mono:latest"
  stage: test
  script:
    - dotnet --help
    - mono --help
    - fsharpi --help
  only: *only_dotnet_mono

deploy-dotnet-mono:
  stage: deploy
  image: docker:latest
  script:
    - docker pull "$CI_REGISTRY_IMAGE/dotnet-mono:latest"
    - docker tag "$CI_REGISTRY_IMAGE/dotnet-mono:latest" ameier38/dotnet-mono:latest
    - docker push ameier38/dotnet-mono:latest
  only:
    - master
