stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

build-dotnet-mono:
  stage: build
  image: docker:latest
  script:
    - docker pull ameier38/dotnet-mono:latest || true
    - docker build --cache-from ameier38/dotnet-mono:latest -t ameier38/dotnet-mono:latest dotnet-mono
  only: &only_dotnet_mono
    refs:
      - merge_requests
    changes:
      - dotnet-mono/Dockerfile
    
test-dotnet-mono:
  image: ameier38/dotnet-mono
  stage: test
  script:
    - dotnet --help
    - mono --help
    - fsharpi --help
  only: *only_dotnet_mono

deploy-dotnet-mono:
  stage: deploy
  image: docker:latest
  script:
    - docker pull "$CI_REGISTRY_IMAGE/dotnet-mono:latest"
    - docker tag "$CI_REGISTRY_IMAGE/dotnet-mono:latest" ameier38/dotnet-mono:latest
    - docker push ameier38/dotnet-mono:latest
  only:
    - master
