stages:
  - build
  - test
  - deploy

services:
  - docker:dind

build-dotnet-mono:
  stage: build
  image: docker:latest
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "ameier38/dotnet-mono:$CI_COMMIT_REF_SLUG" .
    - docker push "ameier38/dotnet-mono:$CI_COMMIT_REF_SLUG"
  only:
    changes:
      - dotnet-mono/Dockerfile
    
test-dotnet-mono:
  image: "ameier38/dotnet-mono:$CI_COMMIT_REF_SLUG"
  stage: test
  script:
    - dotnet --help
    - mono --help
    - fsharpi --help
  dependencies:
    - build-dotnet-mono

deploy-dotnet-mono:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" index.docker.io
    - docker build -t "index.docker.io/ameier38/dotnet-mono:$CI_COMMIT_REF_SLUG" .
    - docker push "index.docker.io/ameier38/dotnet-mono:$CI_COMMIT_REF_SLUG"
  only:
    - develop
  dependencies:
    - test-dotnet-mono
