stages:
  - build
  - test
  - deploy

services:
  - docker:dind

build-dotnet-mono:
  stage: build
  image: docker:latest
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY/ameier38/dotnet-mono:$CI_COMMIT_SHA" dotnet-mono
    - docker push "$CI_REGISTRY/ameier38/dotnet-mono:$CI_COMMIT_SHA"
  only: &only_dotnet_mono
    refs:
      - merge_requests
    changes:
      - dotnet-mono/Dockerfile
    
test-dotnet-mono:
  image: "$CI_REGISTRY/ameier38/dotnet-mono:$CI_COMMIT_SHA"
  stage: test
  script:
    - dotnet --help
    - mono --help
    - fsharpi --help
  only: *only_dotnet_mono

deploy-dotnet-mono:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" index.docker.io
    - docker build -t "index.docker.io/ameier38/dotnet-mono:$CI_COMMIT_SHA" dotnet-mono
    - docker push "index.docker.io/ameier38/dotnet-mono:$CI_COMMIT_SHA"
  only:
    - develop
