version: '1.0'
stages:
  - build
  - push
steps:
  check_dotnet_mono:
    stage: build
    title: Check dotnet-mono
    image: codefreshio/git-image:latest
    working_directory: dotnet-mono
    commands:
      - export GIT_BRANCH="${{CF_BRANCH}}"
      - bash export_files_changed.sh
  build_dotnet_mono:
    stage: build
    title: Build dotnet-mon
    type: build
    image_name: ameier38/dotnet-mono
    working_directory: ${{check_dotnet_mono}}
    dockerfile: Dockerfile
    when: &when_files_changed
      condition:
        all:
          filesChanged: 'Number("${{FILES_CHANGED}}") > 0'
  push_dotnet_mono:
    title: Push dotnet-mono
    type: push
    candidate: ${{build_dotnet_mono}}
    tag: ${{CF_BRANCH}}
    credentials:
      username: ${{dockerUsername}}
      password: ${{dockerPassword}}
    when: *when_files_changed
