version: '1.0'
stages:
  - build
  - test
  - push
steps:
  build_dotnet_mono_sdk:
    stage: build
    title: Build dotnet-mono-sdk
    type: build
    image_name: ameier38/dotnet-mono-sdk
    tag: "2.1.6"
    working_directory: dotnet-mono-sdk
    dockerfile: Dockerfile
  build_dind_git_kube_faas:
    stage: build
    title: Build dind-git-kube-faas
    type: build
    image_name: ameier38/dind-git-kube-faas
    tag: "latest"
    working_directory: dind-git-kube-faas
    dockerfile: Dockerfile
  push_dotnet_mono_sdk:
    stage: push
    title: Push dotnet-mono-sdk
    type: push
    candidate: ${{build_dotnet_mono_sdk}}
    tag: "2.1"
    registry: dockerhub
    when: 
      branch:
        only:
          - master
  push_dind_git_kube_faas:
    stage: push
    title: Push dind-git-kube-faas
    type: push
    candidate: ${{build_dind_git_kube_faas}}
    tags: 
      - "latest"
    registry: dockerhub
    when: 
      branch:
        only:
          - master
