version: '1.0'
stages:
  - build
  - test
  - push
steps:
  build_dotnet_mono_2_2:
    stage: build
    title: Build dotnet-mono 2.2
    type: build
    image_name: ameier38/dotnet-mono
    tag: "2.2"
    working_directory: dotnet-mono
    dockerfile: Dockerfile
    build_arguments:
      - SDK_VERSION=2.2
  build_dotnet_mono_2_1_6:
    stage: build
    title: Build dotnet-mono 2.1.6
    type: build
    image_name: ameier38/dotnet-mono
    tag: "2.1.6"
    working_directory: dotnet-mono-pre
    dockerfile: Dockerfile
    build_arguments:
      - SDK_VERSION=2.1.6
  push_dotnet_mono_2_2:
    stage: push
    title: Push dotnet-mono 2.2
    type: push
    candidate: ${{build_dotnet_mono_2_2}}
    tags: 
      - "2.2"
    registry: dockerhub
    when: 
      branch:
        only:
          - master
  push_dotnet_mono_2_1_6:
    stage: push
    title: Push dotnet-mono 2.1.6
    type: push
    candidate: ${{build_dotnet_mono_2_1_6}}
    tags: 
      - "2.1.6"
    registry: dockerhub
    when: 
      branch:
        only:
          - master
